name: 自動更新庫存到 Google Sheet # 工作流程的名稱

on:
  schedule:
    # 測試排程：每 5 分鐘執行一次 (UTC 時間 04:53，對應台灣時間 12:53)
    - cron: '*/5 * * * *' 

  # 允許手動觸發工作流程
  workflow_dispatch:

jobs:
  update_inventory:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 環境來運行此工作

    steps:
    - name: 檢查程式碼 # 下載您的儲存庫代碼
      uses: actions/checkout@v4

    - name: 設定 Python 環境 # 設定 Python 版本
      uses: actions/setup-python@v5 # <-- 這裡已修正為斜線 "/"
      with:
        python-version: '3.9' # 或您使用的 Python 版本，例如 '3.10', '3.11'

    - name: 安裝 Python 套件 # <-- 整合為一個步驟，確保安裝所有依賴
      run: |
        python -m pip install --upgrade pip
        pip install pandas selenium gspread oauth2client pytz # <-- 已包含 pytz

    - name: 安裝 Chrome 瀏覽器 # 安裝 Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: 安裝 ChromeDriver
      run: |
        # 移除多餘的空行和縮排，保持腳本清晰
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        echo "Detected Chrome Version: $CHROME_VERSION"
        
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.version")
        echo "Detected ChromeDriver Version: $CHROMEDRIVER_VERSION"
        
        CHROMEDRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
        
        wget "$CHROMEDRIVER_URL" -O chromedriver.zip
        unzip chromedriver.zip
        
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        
        sudo chmod +x /usr/local/bin/chromedriver    


    - name: 執行 Python 腳本 # 運行您的 Python 腳本
      env:
        # 從 GitHub Secrets 載入敏感資訊
        IBIZA_EMAIL: ${{ secrets.IBIZA_EMAIL }}
        IBIZA_PASSWORD: ${{ secrets.IBIZA_PASSWORD }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python inventory_updater.py

    # <-- 這裡移除了重複的「安裝套件」步驟
